"""
database.py — Compatibility shim.

All application code (admin.py, public.py, auth.py) imports from this module.
This shim now delegates everything to database_sa (SQLAlchemy) so the rest of
the app needs zero changes.

The old sqlite3 implementation has been archived to database_sqlite_legacy.py
and is no longer used by the application.
"""
from database_sa import *  # noqa: F401, F403 — intentional re-export
from database_sa import (  # explicit re-export for IDEs
    init_db,
    create_default_admin,
    init_default_settings,
    create_default_pricing_packages,
    get_user_by_email,
    get_user_by_id,
    get_all_income,
    add_income,
    delete_income,
    get_total_income,
    get_all_expenses,
    add_expense,
    delete_expense,
    get_total_expenses,
    get_all_customers,
    get_customer,
    add_customer,
    update_customer_payment,
    delete_customer,
    get_total_pending_balance,
    get_all_invoices,
    generate_invoice_number,
    add_invoice,
    update_invoice_status,
    delete_invoice,
    get_all_assets,
    add_asset,
    delete_asset,
    get_total_asset_value,
    get_all_gallery_images,
    get_published_gallery_images,
    add_gallery_image,
    toggle_gallery_publish,
    delete_gallery_image,
    get_website_settings,
    update_website_settings,
    get_income_by_date_range,
    get_expenses_by_date_range,
    get_recent_transactions,
    get_all_messages,
    get_unread_messages_count,
    add_contact_message,
    mark_message_read,
    delete_message,
    get_all_pricing_packages,
    get_active_pricing_packages,
    get_pricing_package,
    add_pricing_package,
    update_pricing_package,
    delete_pricing_package,
    toggle_pricing_package,
    get_all_hero_images,
    add_hero_image,
    delete_hero_image,
    log_audit,
    get_recent_audit_logs,
    # Phase 6: restore functions for soft-deleted entities
    restore_income,
    restore_expense,
    restore_customer,
    restore_invoice,
    restore_gallery_image,
)
